version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - yum update -y
      - yum install -y git java-11-amazon-corretto-devel docker https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm
      - which docker || (echo "Docker is not installed" && exit 1)
      - systemctl start docker
      - git init
      - release_tag=$(curl -s https://api.github.com/repos/opensearch-project/opensearch-migrations/releases/latest | jq -r ".tag_name")
      - git remote add -f origin https://github.com/opensearch-project/opensearch-migrations.git
      - git config core.sparseCheckout true
      - echo -e 'deployment\nTrafficCapture\nFetchMigration\nVERSION' > .git/info/sparse-checkout
      - git checkout tags/$release_tag
      - cd deployment/cdk/opensearch-service-migration
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - export AWS_DEFAULT_REGION=us-east-1
      - cdk bootstrap --c contextId=demo-deploy
      - cdk deploy "*" --c contextId=demo-deploy --require-approval never --concurrency 3
